unstable_features = true
version = "Two"
use_small_heuristics = "Max"

condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true

imports_granularity = "Module"
group_imports = "StdExternalCrate"
